---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: kimai
  labels: { app: mariadb }
spec:
  replicas: 1
  selector: { matchLabels: { app: mariadb } }
  strategy:
    type: Recreate
  template:
    metadata:
      labels: { app: mariadb }
    spec:
      securityContext:
        fsGroup: 1001
        fsgroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: fix-perms
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "chown -R 1001:1001 /bitnami/mariadb || true; chmod -R g+rwX /bitnami/mariadb",
            ]
          securityContext: { runAsUser: 0 }
          volumeMounts:
            - name: data
              mountPath: /bitnami/mariadb
      containers:
        - name: mariadb
          image: docker.io/bitnamilegacy/mariadb:10.6.12-debian-11-r16
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MARIADB_DATABASE # Bitnami envs
              valueFrom:
                { secretKeyRef: { name: kimai-secrets, key: DB_DATABASE } }
            - name: MARIADB_USER
              valueFrom: { secretKeyRef: { name: kimai-secrets, key: DB_USER } }
            - name: MARIADB_PASSWORD
              valueFrom:
                { secretKeyRef: { name: kimai-secrets, key: DB_PASSWORD } }
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                { secretKeyRef: { name: kimai-secrets, key: DB_ROOT_PASSWORD } }
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /bitnami/mariadb
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: kimai-mariadb }
