---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: kimai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests: { storage: 2Gi }
  storageClassName: longhorn-retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kimai-var
  namespace: kimai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests: { storage: 1Gi }
  storageClassName: longhorn-retain