---
apiVersion: v1
kind: Secret
metadata:
  name: kimai-secrets
  namespace: kimai
type: Opaque
stringData:
  # --- DB creds (used by MariaDB and Kimai) ---
  DB_DATABASE: kimai
  DB_USER: kimai
  DB_PASSWORD: CHANGEME-dbpass
  DB_ROOT_PASSWORD: CHANGEME-root
  # exact serverVersion matters (match your MariaDB image)
  DATABASE_URL: "mysql://kimai:CHANGEME-dbpass@kimai-mariadb:3306/kimai?charset=utf8mb4&serverVersion=10.6.12-MariaDB"
  # --- Kimai app bootstrap (first-run admin gets created if missing) ---
  # ADMINMAIL: admin@example.com
  # ADMINPASS: CHANGEME-admin
  # APP_SECRET: CHANGEME-appsecret
