---
apiVersion: v1
kind: Namespace
metadata:
  name: uptime-kuma

---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  type: ClusterIP
  ports:
    - name: kuma-web-ui
      protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    app: uptime-kuma

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: kuma.apps.lab1.hbf.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kuma-web-ui
                port:
                  name: kuma-web-ui
